### PR TITLE
Nairdomain merge

### PR DESCRIPTION
**Pull request by adrianytw**
its mainly about page kek + clean up
https://nairdomain.isstrack.pages.dev/about

### CODE REVIEW

**Comment by adrianytw** [comment]
its mainly about page kek + clean up
https://nairdomain.isstrack.pages.dev/about
but this time it runs >.<

**Comment by benjy1232** [comment]
Just double checking, did this get rid of the need to use `--force` when running npm install with the changes in the `package.json`

**Comment by benjy1232** [comment]
other than that, changes seem sane n what not

**Comment by adrianytw** [comment]
> Just double checking, did this get rid of the need to use `--force` when running npm install with the changes in the `package.json`

didnt know we were forcing lemme check

**Comment by adrianytw** [comment]
i tested by making `npm install` in Dockerfile without --force, 
seems to work  :3

**Comment by benjy1232** [comment]
> i tested by making `npm install` in Dockerfile without --force, seems to work :3

Aight sounds good, remove the --force from dockerfile n I'll approve 🫡

**Comment by adrianytw** [comment]
🫡 done 😼

**Comment by adrianytw** [comment]
just realized page has no title kek

**Review by benjy1232 — APPROVED** [review]

**Pull request merged**
